### ISSUE TITLE
Polish the quick start document

### ISSUE THREAD

**Issue by RongtongJin** [apache/rocketmq-site#435]
Polish the quick start document

**Comment by buptxxb65** [comment]
@RongtongJin Hi Rongtong! In order to participate the GSoC program with RocketMQ, I tried to establish the RocketMQ in my laptop. However, I found that there might be a mistake in the English version document.

In ProducerExample.java and PushConsumerExample.java, topic is incorrectly written as "YourTopic", but we didn't create this topic in advance. I think it should be the same as Chinese version document, written in "TestTopic".

I have made a PR to fix this mistake. https://github.com/apache/rocketmq-site/pull/528
